### ISSUE TITLE
Calls die without returning a response.

### ISSUE THREAD

**Issue by jrmassoni** [intel/NMPRK#1]
Calls should return a response with an error code if they fail, no error code is return and the commands sometimes just die.  This doesn't allow the programmer to try to recover or exit gracefully.  An example of this is the getPolicy command sometimes dies and displays the message "Failed", not letting me know why it failed, or allowing me to retry the command, or allowing me to exit my program gracefully.

**Comment by jrmassoni** [comment]
This was partly a problem of some debug code existing that needed to be removed (oops). The other issues related to this is that in some cases the code was just never finished to add in the messages.  Or the code actually modifies the return code from what IPMI returns to a different value, and that the code is returned as part of a message.  There needs to be a more unified way to return errors to the parent application so it can know what is going on and can take action on it.

**Comment by yilongx** [comment]
when can we get the latest version for retest?  shall we get the source from this github or release tar ball?

**Comment by jrmassoni** [comment]
Updated the code to return IPMI values for calls.  Now in the test code you can test for the IPMI code to determine what the error was and then decide on that what actions to take.

**Comment by jrmassoni** [comment]
Actually there are still many cases in reading the SEL, SDR and FRU where it returns with just a false and no error.  What am I suppose to do and why did it die?  These should return some type of error code indicating why they died. Reopening this defect.

**Comment by jrmassoni** [comment]
The error coding has greatly been improved in the coming Sept 2012 release.  We are sure there are still cases where an error code and message are not returned, but it should be a lot less.  Will keep this defect open until we have confidence we have found nearly all cases, and then handle them on a case by case basis.

**Comment by jrmassoni** [comment]
This have been greatly improved for the September release.  Any future bugs in this area will be handled on a case by case basis.
