### ISSUE TITLE
need to return response data for completion code 0x80/0x81 when getting NM policies 

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#10]
Currently, the fucntion ipmi_openipmi_send_cmd() in ipmi/src/modules/nm_dcmi/linux/open.cpp only saves the response data for caller when the completion code equals 0x00. 

However, when getting the NM policy(netFn=0x2e, cmd=0xc2), the response data returned with completion 0x80/0x81 is useful to the user in querying all the existing polices or domains. So we'd better to return that kind of information to the user.

**Comment by jrmassoni** [comment]
IPMI codes have now been brought out to the calling program.  Please retest.
