### ISSUE TITLE
Function "delSelRecord" can't delete one record from SEL

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#11]
when i use Function "delSelRecord" to delete one record from SEL, but i found it has the same entries before delete and after.
Function "delSdrRecord" has the same phenomenon.

the test output as follows:
————————————————————————————————————————
Before delete：
###### 

Attempting to get SEL Info..... Passed
            Repo Entries: 129
            Repo Free Space: 63180 Bytes

after delete：
###### 

Attempting to delete the record from the SEL.....here?
did we get here
Passed
     delete one record from SEL successfully! 

Attempting to get SEL Info..... Passed
            Repo Entries: 129
            Repo Free Space: 63180 Bytes

**Comment by jrmassoni** [comment]
Tried debugging this command.  The code now looks fine and sends the delete SEL record, but returns an error that the command is not recognized.  Will leave it for further debugging in the future.

**Comment by yilongx** [comment]
This issue exists in new version.

**Comment by jrmassoni** [comment]
When you get SelInfo it now passes back a flag indicating whether the Server under test supports this feature. If the server does support the feature, then it should work.  Note that the feature can only delete either the first or the last record.

**Comment by yilongx** [comment]
Now our platform doesn't support SEL delete function, so we can't verify this issue. Could you help me confirm this issue? Thanks.

**Comment by jrmassoni** [comment]
This function was tested and verified in HF2.

**Comment by yilongx** [comment]
Thanks
