### ISSUE TITLE
The function nmprk::translation::setPolicyStatus() calls nmprk::translation::nm_dnm::nm_dnm_setPolicy to make a policy status

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#2]
The function nmprk::translation::setPolicyStatus() calls  nmprk::translation::nm_dnm::nm_dnm_setPolicy to set a policy status. But in namespace nmprk::translation::nm_dnm, there is a function named nm_dnm_setPolicyStatus. I think this is a mistake.

**Comment by jrmassoni** [comment]
This issue will be fixed in the next release.

**Comment by yilongx** [comment]
It seems that this issue has not been modified.

**Comment by jrmassoni** [comment]
It was modified. The function setPolicyStatus no longer calls sePolicy.  The function is also used in the testIpmi.exe program to both enable and disable a policy and works.  Note: You must follow the NM code path.

**Comment by yilongx** [comment]
Sorry, i made a mistake, it was modified.
