### ISSUE TITLE
Can't call setPolicy() more than once

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#26]
we can't call setPolicy() Several More than once. we may get follow error message if we do it
i think we should call setPolicy() many times.  it only need to update the existing policy nor give an error.
###### 

Attempting to create policy ID = 3..... Failed!
Caught Exception setPolicy(0x03): Code[213] MSG[Command not supported in present state]

**Comment by jrmassoni** [comment]
This is indicating that you can use the command in the present state, which is not a bug.  The issue is something like that the policy is active and must not be active when you modify it. This rule is set up by Node Manager, not the NMPRK.  I will need to investigate it more to see exactly why.
