### ISSUE TITLE
we can't clear SEL records by calling clearSel()

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#29]
we can't clear SEL records by calling clearSel(),  whether it uses the wrong command in Internal processing.

The output of calling clearSel() before and after
###### 

Attempting to get SEL Info..... Passed
            Repo Entries: 138
            Repo Free Space: 63018 Bytes
###### ########################################################################

Attempting to clear out the SEL.....Passed
            Clear SEL successfully! 

Attempting to get SEL Info..... Passed
            Repo Entries: 138
            Repo Free Space: 63018 Bytes

**Comment by yilongx** [comment]
delSelRecord() has the same phenomenon .

**Comment by yilongx** [comment]
SDR deleteSdrRecord() and clearSdr() as well

**Comment by jrmassoni** [comment]
Clear SEL was fixed after providing you the last release.  This is a duplicate of that issue.  Delete Sel still does not work and has its own defect. This is a duplicate issue.  SDR clear, add and delete also do not work correctly and have there own defect.  This is a duplicate issue and therefore will be closed.
