### ISSUE TITLE
How do we insert new data into SDR repository     

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#33]
If I clear all SDR data, how do i  insert the new data into SDR repository.

**Comment by jrmassoni** [comment]
What you wrote must not be correct as the SDR repository and the FRU repository do not have anything to do with each other.  Plus there is no clear FRU repository command.  The latest test application shows how to read the SDR repository, clear the SDR repository and write the SDR repository.  You can then read it again and compare the two files.  As for the FRU, current the read FRU works. There is not clear FRU call.  But the write FRU command does not work correctly.  I am working on that.

**Comment by yilongx** [comment]
I clear the SDR data, but  I want to test add function. what should i do can make it successful?

**Comment by yilongx** [comment]
Could you give me a sample about how to make one SDR  record? Thanks

**Comment by jrmassoni** [comment]
If there is an SDR on your system, then you can run the TESTIPMI and save it into the file testfile.sdr.  You should copy this file and rename it to the name of your server.sdr for safe keeping.  If your SDR is gone on your system, then you must restore it with the one provided for your system.  This should be part of the firmware package for your server.  Once you have used the firmware package to restore the SDR, then save it using into a file using the method I explained using testIpmi application.  The testIpmi application will not work directly with the files obtained in the firmware package as those files have a different format.  The same goes for working with FRU files.  

Do not program another systems SDR file into your server.  The SDR file effects how well your server runs, so you need to only used SDR files for your specific server.

**Comment by yilongx** [comment]
I have recovered the SDR records correctly with ipmitool command, but we still don't know How to manually create a SDR record.

**Comment by jrmassoni** [comment]
I do not know how to create a Sensor Data Record and do not recommend doing so. SDRs are created specific for your Server and effect how well it functions.  Please use the approved SDR file that is provided in the firmware package for your server.  You may obtain the firmware package for your server at Intel.com

**Comment by yilongx** [comment]
ok, that's no problem. may we close it?
