### ISSUE TITLE
we can't  clear all SEL data by calling clearSel() Function.

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#34]
we can't  clear all SEL data by calling clearSel() Function. There is always one SEL record in repository  although we have called clearSel() Function.

**Comment by yilongx** [comment]
whether there is one default record in SEL repository or we can't delete the Newest record. yes?

**Comment by jrmassoni** [comment]
Yes, I believe the event of clearing the SEL is the entry that is entered after the SEL is cleared.

**Comment by yilongx** [comment]
Function "clearSel()" works well in new version "nmprk-RC3-5" without this issue.
