### ISSUE TITLE
“Segmentation fault” when calling getSdrInfo() in out-of-band mode with bridge/channel address set to NM's 

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#5]
“Segmentation fault”  happen when i modify device default bridge and transport  and call getSelInfo(). i think it shuold report parameter error not “Segmentation fault”
Funciton getSdrInfo() and getFruInfo() have the same phenomenon with getSelInfo().

the gdb debug information as follows：
###### 

(gdb) 
nmprk::ipmi::sdr::getSdrInfo (d=0x7fffffffe190) at src/nmprk_ipmi_sdr.cpp:40
40             ret->repoVersion = nmprk::helper::hexStr2Int(rsp.data[0]);
(gdb) 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b79f28 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb)

when i run this test with remote mode and with "sudo", there is no this issue happened.
run command as below:
 $ sudo testIpmi -nm -remote ip passwd

**Comment by jrmassoni** [comment]
This is a reference kit.  The intent was to give developers code that they could take and modify for their purposes and let them add code to check input data to ensure that it is correct before making the call.  In the future we may consider adding more checks to reduce the severity of issues like this, as you suggested, but only after we get the main functionality fully working.

**Comment by yilongx** [comment]
This issue doesn't appear in version nmprk-RC3-5,  it reports error message. we think it is reasonable

##########################################################################
Attempting to get SDR Info..... 
Error: getSDRInfo Exception - Code: 0xc1, Msg: Invalid or unsupported command
