### ISSUE TITLE
we must modify the file "nmprk_translation.h" after we install nmprk

### ISSUE THREAD

**Issue by yilongx** [intel/NMPRK#9]
In order to run out test program, we must modify the file "nmprk_translation.h" after we install nmprk SDK to resolve header files Relative path issue.

**Comment by jrmassoni** [comment]
We install the PDK on 6 different systems when we test it, 3 Linux and 3 Windows.  Compile it on all and never have had to change nmprk_translation.h.  What exactly do you have to change in the file?

**Comment by yilongx** [comment]
if you are  free , you may check  the step4 of the file nmprk-release1.1\docs\UsingTheNmprkLibraryInLinux.txt under the nmprk-release1.1 package

**Comment by jrmassoni** [comment]
Yes, as part of the current install you must modify the path, but that is done for you in the install script.  Are you saying that because you need to do that, it is a bug or are you saying there is something else you need to modify?  Still don't understand what you are saying is the issue.

**Comment by yilongx** [comment]
There is no this issue in new version.
